pipeline {
    agent any
    environment {
        PROJECT= 'expense'
        COMPONENT= 'backend'
        def apiVerson=''

    }
    stages{
        stage('Read version'){
            steps{script {
                def packageJson = readJSON file: 'backend/package.json'
                apiVerson= packageJson.version
                echo "$apiVerson"
            }

            }
        }
        stage('install dependencies'){
            steps{
                sh '''
                npm install
                '''
            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}